services:
  - type: web
    name: flask-discord-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: DISCORD_WEBHOOK
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: FLASK_HOST
        value: 0.0.0.0
      - key: FLASK_PORT
        value: 10000
